Occupancy alert =

VAR _OccupiedSurface =
VAR _TotalSurface =
VAR _TargetOccupancy = [Target Occupancy Rate] ## ça peut être un paramètre que tu crées

VAR _OccupancyRate = DIVIDE(_OccupiedSurface, _TotalSurface)

VAR _Gap = _OccupancyRate - _TargetOccupancy

VAR _GapFormatted = FORMAT(_Gap, "+0.0%, -0.0%")

VAR _ShowAlert = ABS(_Gap) > 0.05

VAR _Message = 
	IF(
		_ShowAlert,
		"immeuble sous occupé",
		"immeuble bien occupé"
	)

RETURN
	_Message