Occupancy alert =

VAR _OccupiedSurface =
VAR _TotalSurface =
VAR _TargetOccupancy = [Target Occupancy Rate] ## ça peut être un paramètre que tu crées


VAR Gap_pct = DIVIDE(_OccupiedSurface, _TotalSurface)

VAR Formatting = FORMAT([Gap_pct], -%0.0, +%0.0)

VAR Abs = ABS(Formatting)

RETURN
